add the yml file

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -39,32 +39,32 @@ jobs:
         run: npx playwright test
         continue-on-error: true
 
-      # Step 6: Install Allure Command Line Tool
-      - name: Install Allure Command Line Tool
-        run: npm install -g allure-commandline
+      # # Step 6: Install Allure Command Line Tool
+      # - name: Install Allure Command Line Tool
+      #   run: npm install -g allure-commandline
 
-      # Step 7: Generate Allure Single HTML Report
-      - name: Generate Allure Single HTML Report
-        run: |
-          rm -rf allure-report
-          allure generate --single-file allure-results --clean -o allure-report || echo "Report generation failed"
-        continue-on-error: true
+      # # Step 7: Generate Allure Single HTML Report
+      # - name: Generate Allure Single HTML Report
+      #   run: |
+      #     rm -rf allure-report
+      #     allure generate --single-file allure-results --clean -o allure-report || echo "Report generation failed"
+      #   continue-on-error: true
 
-      # Step 8: Send Email with Allure Report as Attachment
-      - name: Send Email with Allure Report
-        uses: dawidd6/action-send-mail@v3
-        with:
-          server_address: smtp.gmail.com
-          server_port: 465
-          username: ${{ secrets.EMAIL_USERNAME }}
-          password: ${{ secrets.EMAIL_PASSWORD }}
-          subject: "Allure Test Report"
-          body: "The Allure report is attached as a single HTML file. Open it in your browser to view the test results."
-          to: "nassirctg1234@gmail.com"
-          from: ${{ secrets.EMAIL_USERNAME }}
-          attachments: allure-report/index.html
+      # # Step 8: Send Email with Allure Report as Attachment
+      # - name: Send Email with Allure Report
+      #   uses: dawidd6/action-send-mail@v3
+      #   with:
+      #     server_address: smtp.gmail.com
+      #     server_port: 465
+      #     username: ${{ secrets.EMAIL_USERNAME }}
+      #     password: ${{ secrets.EMAIL_PASSWORD }}
+      #     subject: "Allure Test Report"
+      #     body: "The Allure report is attached as a single HTML file. Open it in your browser to view the test results."
+      #     to: "nassirctg1234@gmail.com"
+      #     from: ${{ secrets.EMAIL_USERNAME }}
+      #     attachments: allure-report/index.html
 
-      # Step 9: Fail Workflow if Tests Failed
-      - name: Fail Workflow if Tests Failed
-        if: failure()
+      # # Step 9: Fail Workflow if Tests Failed
+      # - name: Fail Workflow if Tests Failed
+      #   if: failure()
         run: exit 1
